### ISSUE TITLE
Backlash compensation causes tracking jitter/oscillations

### ISSUE THREAD

**Issue by jgottula** [bgottula/track#31]
We observed that backlash compensation as currently implemented causes the mount to oscillate back and forth when tracking a relatively stationary object like a planet or a star. This is not too surprising. It is anticipated that this problem will not show up when tracking fast-moving objects like LEO satellites because the slew rates will be high and should rarely change direction.

One idea for fixing this problem is to use knowledge of the apparent motion of the object to decide when to apply backlash compensation. For example, when tracking a star based on its RA/DEC coordinates, the apparent motion in Az-Alt is known. This knowledge can be used to determine whether backlash compensation should be enabled or disabled in either axis. Compensation will only be enabled or disabled when the sign of the object's motion vector changes. This is in contrast to the current approach where the mount's slew direction determines whether compensation is applied. The slew direction may change several times while the loop is converging and based on our observation this can lead to unwanted oscillations.

**Comment by bgottula** [comment]
The alternative approach in the description has been implemented but not tested.

**Comment by bgottula** [comment]
The code has been used with the fix and I do not recall seeing evidence of this problem when using blind tracking to point at stars or planets. Considering this resolved.
