### ISSUE TITLE
Create configuration files or add reasonable defaults for program arguments

### ISSUE THREAD

**Issue by bgottula** [bgottula/track#34]
During an observation session there is a lot to keep track of--hardware setup, cables management, pointing the scope manually during alignment, looking up and preparing for satellite passes, diagnosing problems, etc. There is also a lot of stress due to the limited window of time during which bright satellites are visible. Therefore it is imperative to be able to run each of the applications quickly. One of the obstacles to running programs quickly is having to specify too many command-line arguments to each program. Wherever possible, reasonable defaults should be chosen or configuration files generated such that arguments do not need to be typed out during the time-critical observing session.

**Comment by jgottula** [comment]
Brett needs to actually use the config file functionality I added to this project, dammit!
