### ISSUE TITLE
Automatically set webcam controls from Python

### ISSUE THREAD

**Issue by jgottula** [bgottula/track#40]
Instead of requiring the user to remember to do separate webcam setup via the `v4l2-ctl` CLI utility, set the controls to the desired values within the Python scripts themselves, preferably via `v4l2capture`, or via `v4l2` when necessary.

Most important controls:
- [x] Automatic gain: always disable
- [x] JPEG compression quality: always max allowed
- [x] Exposure: optional cmdline param with reasonable default value?

Less important controls:
- [ ] Brightness
- [ ] Contrast
- [ ] Gamma
- [ ] Sharpness
- [ ] Power line frequency

**Comment by jgottula** [comment]
Implemented the 3 higher-priority tasks.

**Comment by bgottula** [comment]
The default values for the remaining controls seem to work just fine. Cookie Monster criterion achieved! :cookie:
