### ISSUE TITLE
Organize files into a Python package

### ISSUE THREAD

**Issue by bgottula** [bgottula/track#49]
I'm still a n00b when it comes to Python packages and how they should be structured. Use some of the guides out there and organize this project in a sane manner.

http://docs.python-guide.org/en/latest/writing/structure/
https://python-packaging.readthedocs.io/en/latest/minimal.html

**Comment by jgottula** [comment]
See also #37 when working on this.

**Comment by bgottula** [comment]
The repository has been reorganized as a package.
